name: Validate code and run tests

on: push

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.5
      - name: ğŸ“¦ Install dependencies
        run: bun install
      - name: ğŸ”¦ Run linter
        run: bun lint
      - name: ğŸª Check TypeScript
        run: bun typecheck

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.5
      - name: ğŸ“¦ Install dependencies
        run: bun install
      - name: ğŸ§ª Run tests
        run: bun test

  monorepo-lint:
    name: Monorepo lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ğŸ” Run monorepo lint
        uses: QuiiBz/sherif@v1
